### ISSUE TITLE
Can not see things like planner when not logged in

### ISSUE THREAD

**Issue by maxandersen** [openshiftio/openshift.io#1501]
Goto https://openshift.io/openshiftio/openshiftio/plan as logged out user.

Expect: can see the issues and browse them, but not be able to created/edit before logged in.

Actually: shows up with blank page, only top openshift planner is visible.

## Impacts
#2091 Anonymous user should see features as `released` ie: Production only

**Comment by kwk** [comment]
@maxandersen  I cannot tell why, but this is what I see, which should resemble what you've described:

![bildschirmfoto von 2017-12-04 18-58-31](https://user-images.githubusercontent.com/193408/33567970-279bac12-d925-11e7-9a3d-7d9f5c81d3c8.png)

For a particular work item, the page loads fine:

![bildschirmfoto von 2017-12-04 18-59-15](https://user-images.githubusercontent.com/193408/33568032-5e7370a8-d925-11e7-8a44-7cd02e3e3454.png)

The beginning of the logs:
![bildschirmfoto von 2017-12-04 19-01-58](https://user-images.githubusercontent.com/193408/33568148-c46ddfce-d925-11e7-9580-91f1b0922f65.png)

The first error I see:
![bildschirmfoto von 2017-12-04 19-02-08](https://user-images.githubusercontent.com/193408/33568128-b4229de4-d925-11e7-942d-66f28da6459b.png)

**Comment by joshuawilson** [comment]
@alexeykazakov @sbose78 any ideas on this?
@c-koehler are you sure this has nothing to do with the changes you made?

**Comment by alexeykazakov** [comment]
I see 401 from `PATCH https://auth.openshift.io/api/users` which makes perfect sense because there is no user token in the request. I have no idea what was changed on the UI side to break anonymous access to Planer.

**Comment by alexeykazakov** [comment]
> I see 401 from PATCH https://auth.openshift.io/api/users which makes perfect sense because there is no user token in the request. I have no idea what changed on the UI side to break anonymous access to Planer.

I think this PATCH is called to update the user's context to add the space to the list of recent spaces. I think we always had it. So, not sure if this 401 is related to the issue.

**Comment by maxandersen** [comment]
> @c-koehler are you sure this has nothing to do with the changes you made?

he stated his changes hadn't been merged yet thus this does not seem likely to be the reason. Looks like a planner frontend issue.

**Comment by c-koehler** [comment]
I went looking in a `git bisect` kind of way to discover where this started happening. Originally I tried finding where it started and found out that whatever is causing this appears to be happening a lot farther back in time.

`6b0a9249bd2c8d39c05c33696d5fc27b9b5d46fe` (16 Oct) - Has the same error

`484371eb9258752f48f3b6911e4b1f599f5784bb` (12 Oct) - Has some different kind of error:
```can't open this one even after a `rm -rf node_modules`
Uncaught Error: Cannot find module "./locale"

?	913bf58d39ec0c07b65e91c1585a1ecf127dda87

?	0d033a2f4a81fa463c2cc5709e4034640e9434d6

?	5e29e7d51c296aaff5ca845e6480562cc6e58f4e

**Comment by jiekang** [comment]
I think it will be difficult to go back in time in the f8-ui repository and have true tests against production if the API URL's that the repository targets have changed.

**Comment by vikram-raj** [comment]
This issue has been resolved but it is not on prod yet but you can check it on prod-prev. Hence, closing this.

**Comment by maxandersen** [comment]
is this in prod yet ? i'm still not seeing issues unless i'm logged in and have enabled experimental ?

**Comment by qodfathr** [comment]
@maxandersen,  anonymous users only have access to released features, so I would not expect Planner to be visible to them. But this does bring up a larger concern that wherever we are using feature flags, we need to gracefully handle the use cases of anonymous browsing. It should not error our; rather, it should behave as if the user is set to Released level.

**Comment by maxandersen** [comment]
the first version of the experimental allowed one to view the work items on direct urls. That worked pretty well.

This does mean we can't share links to planner team work items and prevents planner adoption for other teams as we can't share without the receiver has an active openshift.io account.

**Comment by michaelkleinhenz** [comment]
As far as I can see, the feature *is supposed to be enabled* in the Platform code, but it does not work. While the feature resolving actually should make the Planner available for non-logged in users, the initial feature resolving returns a 401 for ´/api/features´ (note no additional extra path there). I think this call is being made here:

´context.service.ts::changeContext(navigation: Observable<Navigation>)´ in line 263.

I think this throws an error when a 401 is encountered. I did not follow the chain as it diverts quickly, but I would think this caused the error intercepted somewhere and then the user gets redirected to the error page.

Not really sure if the 401 is "wrong" or the handling on Platform there, but fixing either would re-enable readonly access I think.

The req that returns the 401 on non-logged in users is ´https://api.prod-preview.openshift.io/api/features?names=Applications&names=Deployments&names=Environments&names=Planner´

**Comment by stevengutz** [comment]
We need to turn this back on so we in Development can actually use the Planner.  Otherwise, as Max notes, our own teams will never adopt Planner.  We need to get teams to move because there is no hierarchy in GitLab and it is a nightmare to plan/track anything.

**Comment by michaelkleinhenz** [comment]
Looking at is a bit more, this is not limited to Planner. I get the same behaviour on all deep links wherever they go.

I'd say the Unleash service is just rejecting all requests without a valid token. The service returns:

`{"errors":[{"code":"jwt_security_error","detail":"missing header \"Authorization\"","id":"5wx5mf6G","status":"401","title":"Unauthorized"}]}`

**Comment by corinnekrych** [comment]
@michaelkleinhenz I've fixed it in https://github.com/openshiftio/openshift.io/issues/2064 sorry I missed that one. Pr is there too for review.

**Comment by michaelkleinhenz** [comment]
@corinnekrych looking at the code, I'd say that the problem is more in how Unleash responds than in Platform code. Is it correct to block all requests to Unleash without Auth header? Seems hash to me. I'd expected Unleash to be more fine granular. @xcoulon

**Comment by corinnekrych** [comment]
@michaelkleinhenz we'll change that indeed. here is: https://github.com/openshiftio/openshift.io/issues/2091

**Comment by nimishamukherjee** [comment]
@michaelkleinhenz can we close this based on #2091?

**Comment by nimishamukherjee** [comment]
Closing this issue as platform's feature toggle handles this use case now.
